// This file is for demo purposes only.
// Do not attempt to execute it.

const asyncPromise1 = new Promise( ( resolve, reject ) =>
    // ...
    resolve( callbackArg1 );
    // ...
).then( callbackArg1 => {
    // ...
    const asyncPromise2 = new Promise( ( resolve, reject ) => {
        // ...
        resolve( callbackArg2 );
        // ...
    } );
    return asyncPromise2;
} ).then( callbackArg2 => {
    // ...
    const asyncPromise3 = new Promise( ( resolve, reject ) => {
        // ...
        resolve( callbackArg3 );
        // ...
    } );  
    return asyncPromise3;  
} ).then( callbackArg3 => {
    // ... 
} );